# Generated by Django 3.1.14 on 2024-08-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20240801_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
