# Generated by Django 3.1.14 on 2024-07-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthinfo', '0003_auto_20240730_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(max_length=25),
        ),
    ]
