# Generated by Django 4.2.6 on 2024-07-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsAndLogin', '0002_auto_20240730_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
